<?php
/**
 * Created by PhpStorm.
 * User: air
 * Date: 14-7-27
 * Time: 上午8:25
 */

namespace cabbage\modules\linkage;

use Yii;
use yii\web\AssetBundle;

class Select2Asset extends AssetBundle{
    public $depends = [
        'yii\bootstrap\BootstrapPluginAsset'
    ];

    public $css = [
        'select2.css',
    ];

    public $js = [
        'select2.min.js',
    ];

    public function init()
    {
        $this->sourcePath = __DIR__ . '/assets/select2';
        parent::init(); // TODO: Change the autogenerated stub

    }
}